apiVersion: v2
name: extra-deploy
version: 1.0.5
description: Simple wrapper of `bitnamicharts/common` for deploying extra resources via helm chart
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  # renovate: datasource=docker depName=registry-1.docker.io/bitnamicharts
  version: 2.19.3
type: application
annotations:
  org.opencontainers.image.source: https://github.com/A1994SC/helm
