{{- if .Values.auth.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "standardnotes.name" .) .Values.auth.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "standardnotes.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "standardnotes.name" .) .Values.auth.name | trunc 63 | trimSuffix "-" }}
  minReplicas: {{ .Values.auth.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.auth.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: {{ .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
