apiVersion: v2
name: wrapper
version: 1.2.8
description: Adds extra supporting packages
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  # renovate: datasource=docker depName=registry-1.docker.io/bitnamicharts
  version: 2.19.0
type: application
annotations:
  org.opencontainers.image.source: https://github.com/A1994SC/helm
