{{- /* Used for GitOps on a package's Helm chart */ -}}
{{- range $pkg, $vals := .Values.sources -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ $pkg }}
  namespace: {{ dig "namespace" "flux-system" $vals }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" $ | nindent 4 }}
spec:
  url: {{ $vals.url }}
  type: {{ dig "type" "generic" $vals }}
  interval:  {{ dig "interval" "10m0s" $vals }}
{{ end -}}
